# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ActiveRealmSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActiveRealmSample
  pod 'Realm', '~>10'

  target 'ActiveRealmSampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Realm', '~>10'
  end

end
